function(target_disable_rtti target)
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
        target_compile_options(${target} PUBLIC /GR- /EHsc /D_HAS_EXCEPTIONS=0)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
        target_compile_options(${target} PUBLIC -fno-rtti -fno-exceptions)
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
        target_compile_options(${target} PUBLIC -fno-rtti -fno-exceptions)
    endif()
endfunction(target_disable_rtti)
