name: Build & test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Windows - MSVC"
            os: windows-latest
            compiler: cl
          - name: "Ubuntu - Clang"
            os: ubuntu-latest
            compiler: llvm
          - name: "Ubuntu - GCC"
            os: ubuntu-latest
            compiler: gcc

    runs-on: ${{ matrix.os }}
    steps:
    - name: Get number of CPU cores
      uses: SimenB/github-actions-cpu-cores@v1
      id: cpu-cores

    - uses: actions/checkout@v4.1.0
      with:
        submodules: true

    - name: "Setup Cpp"
      uses: aminya/setup-cpp@v1
      with:
        compiler: ${{ matrix.compiler }}
        vcvarsall: ${{ contains(matrix.os, 'windows' )}}
        cmake: true
        ninja: true
        clangtidy: false
        cppcheck: false

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y valgrind libglm-dev libwayland-bin libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

    - name: Configure CMake
      run: >
        cmake -S .
        -B ./build
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ./build --parallel ${{ steps.cpu-cores.outputs.count }} 

    - name: Test
      working-directory: ./build
      run: >
        ctest -j ${{ steps.cpu-cores.outputs.count }} -C Debug --rerun-failed --output-on-failure;
